[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
iroh = "0.95"
iroh-blobs = "0.97"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
futures = "0.3"
flutter_rust_bridge = "=2.11.1"
rand = "0.9"
hex = "0.4"
